server.port: ${SERVER_PORT:5000}

# In a production env. This should be the flag to enable/disable swagger-ui
swagger.ui: ${SWAGGER:true}

endpoints:
  pokemon: ${POKEMON_HOST:}
  translations: ${TRANSLATION_HOST:}

spring:
  application:
    name: pokedex
