services:
  pokedex:
    container_name: pokedex
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - POKEMON_HOST=https://pokeapi.co
      - TRANSLATION_HOST=https://api.funtranslations.com
    ports:
      - "5000:5000"
